# Generated by Django 4.2.30 on 2026-07-03 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Selecao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="alterado em"),
                ),
                (
                    "nome",
                    models.CharField(max_length=64, unique=True, verbose_name="nome"),
                ),
            ],
            options={
                "verbose_name": "Seleção",
                "verbose_name_plural": "Seleções",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Figurinha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="alterado em"),
                ),
                (
                    "code",
                    models.CharField(max_length=16, unique=True, verbose_name="código"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "especial",
                    models.BooleanField(default=False, verbose_name="especial"),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="figurinhas/",
                        verbose_name="imagem",
                    ),
                ),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="alterado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "selecao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="figurinhas",
                        to="figurinhas.selecao",
                        verbose_name="seleção",
                    ),
                ),
            ],
            options={
                "verbose_name": "Figurinha",
                "verbose_name_plural": "Figurinhas",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ColecaoFigurinha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="alterado em"),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=0, verbose_name="quantidade"),
                ),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="alterado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "figurinha",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colecao",
                        to="figurinhas.figurinha",
                        verbose_name="figurinha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coleção",
                "verbose_name_plural": "Coleção",
            },
        ),
    ]
