# Generated by Django 4.2.30 on 2026-07-04 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('figurinhas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecao',
            name='alterado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AddField(
            model_name='selecao',
            name='bandeira',
            field=models.URLField(blank=True, default='', help_text='URL da imagem da bandeira do país (vazio para seções sem bandeira).', max_length=255, verbose_name='bandeira'),
        ),
        migrations.AddField(
            model_name='selecao',
            name='criado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
    ]
